# Generated by Django 3.2.9 on 2021-11-30 09:52

from django.db import migrations, models
import productintro.upload_to


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('TOP', 'Top'), ('PANTS', 'Pants'), ('SKIRT', 'Skirt'), ('OUTER', 'Outer'), ('ACC', 'Acc')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to=productintro.upload_to.uuid_name_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
